### ISSUE TITLE
Choosing install directory

### ISSUE THREAD

**Issue by saun4app** [Squirrel/Squirrel.Windows#1002]
I hope Squirrel allows the users to select install directory.  Here are 2 practical examples:
1. the default drive (e.g., C:) is nearly full.
2. installing an program on SSD to improve performance. 

It is great that Squirrel is "favor of simplicity" (see https://discuss.atom.io/t/how-to-install-atom-on-windows-to-other-places-instead-of-c/27619/7), it would event be better if Squirrel provides flexibility for users who need customization as well.  Using the 80-20 rule as frame of reference, simplicity for 80% of users, customization for 20% of users. Firefox installation is a great example of this approach, provide simplicity for must user, and allows users to customize installation settings.

**Comment by paulcbetts** [comment]
No

**Comment by dizzy-egg** [comment]
@paulcbetts Excellent detailed response. You really took the OP's constructive feedback on board, and gave detailed rebuttals and good justification for his well-reasoned points. 

Will I be using this software?

> No

**Comment by paulcbetts** [comment]
@dizzy-egg I didn't respond because I have answered this question over. and over. and over. and over. again. It's in the wiki, it's on the README why we don't do this.

**Comment by bensku** [comment]
There reads that AppData is used to avoid UAC (to allow silent updates for example). I can understand that. What I don't understand, however, is why cannot Squirrel install to another partition which is fully writable by all users? Is popping a dialog for user (where they may just press enter to continue with default location) too much?

Sorry for bothering you if this has been answered before. I honestly could not find a good explanation for lack of this little feature. Maybe it is there somewhere, but even Google results are mostly about Atom users complaining that they want to choose their installation location; not relevant information.

**Comment by paulcbetts** [comment]
@bensku The reason is that fundamentally, the goal of Squirrel.Windows is to get your app running, as soon as possible. Our goal is that you click on Setup, and the next thing you see is the app running, and that should be **as fast as possible**. Showing dialogs where we ask users questions they shouldn't have to care about, is antithetical to that goal.

That being said, (almost) all Squirrel installs are inherently Portable, once an app is installed, you can actually move that root folder anywhere you want then update the shortcuts. It'll still work and still update itself correctly.

**Comment by bensku** [comment]
Thanks for clarification. I suggest you put this a bit more prominently on README, might make people ask this less often.

Good to know about portability of Squirrel installs. While it is not ideal to manually move folders around, it is certainly better than nothing.

**Comment by RonaldZaZ** [comment]
Maybe a command line switch in the setup.exe for the special cases?
_Setup.exe -installfolder "G:\Apps\Foo"_
Doesn't get in the way of anything.

**Comment by luetm** [comment]
This is what I was thinking. I heard from the project from a podcast but the attitude is really turning me off reading through the issues... :(

**Comment by LukeTOBrien** [comment]
I would say then Squirrel is not a SOLID piece of software, it should be open for extension.  
You could at least allow for an optional `squirrel.config.xml` or `json` file.  
[Custom Events](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md) could also be extended so that at each *stage* and event fires, allowing the developer to provide custom logic and/or custom rendering.

There you go, lots of ideas.... :-)

**Comment by paulcbetts** [comment]
@LukeTOBrian Squirrel is indeed Opinionated Software and will never provide a completely open-ended configurable system. It will only provide a system that does exactly what it says it does, really really well.

**Comment by aDigitalPhantom** [comment]
It's this focing users to installs junk programs on SSDs, and lacking basic install options that makes this crap. I have needing to install software twice. Once to find where it thinks the data to be, and the second time to put the data where I need to to be after creating symlinks. As a software developer there are far better options to give users installation options that will work far better than this.

**Comment by Destroy666x** [comment]
I came here by accident, looking for why I can't install Atom to Program Files, which 99% of Windows apps with an installer are able to do. And after reading few topics, I'm very confused why this is the design choice of this apparently now deprecated, but unfortunately still used by Atom, installer. I respect the devs and their decision as much as I can, but let's just quote: `No`

For any future dev reading this and considering to create an installer or use one for their app - this is not a reasonable choice. It negatively influences:
- security
- automated setups
- people who just like to keep their Windows installation clean or don't want to install to the system drive for one reason or another
etc.

I can't find any positive about it. It's kind of like removing life rings from a ship just because someone thinks it's better for travellers that way. So if anyone considers using Squirrel as an option - once again, please, don't. Inno and different options exist. And if anyone takes/took it over - please reconsider adding this IMO mandatory feature. Thanks.

**Comment by gyan-garcia** [comment]
I was having this problem too and just ended up adding some lines to my app to copy over the whole directory to an accessible location (if it doesn't exist).

if (!Directory.Exists(@"C:\MyApp\")) 
{
   var baseDir = AppDomain.CurrentDomain.BaseDirectory;
   Process.Start("cmd.exe", "/C xcopy " + baseDir+ @"..\..\MyApp C:\MyApp\ /EH");
 }

Love the package BTW.

-Saludos

**Comment by ldeluigi** [comment]
What about getting the installation path from an environment variable? It would not clash with Squirrel goals as it's transparent and doesn't require prompting the user!

**Comment by ScottBeeson** [comment]
I can't believe Intuit uses this... it has ruined an entire day for me.
