### ISSUE TITLE
Hide loadingGif before "--squirrel-firstrun" event is fired.

### ISSUE THREAD

**Issue by gmantri** [Squirrel/Squirrel.Windows#1031]
Hi,

I'm building a desktop application using Electron. For building Windows installer, I am using "electron-squirrel-startup" package (latest version) with default configuration in package.json file i.e.

`if (require('electron-squirrel-startup')) app.quit();`

The installer works great but what I am noticing is the image specified as "loadingGif" stays even after the application starts (sometimes for more than 5 seconds). Same thing happens if standard loadingGif is displayed.

I am curious to know if there's some way to hide this image when the application starts i.e. "--squirrel-firstrun" is fired or hide the application until the installation is completely done.

Please let me know if I need to provide more information. Also please let me know if this is not the right place to ask this question. 

Thanks

**Comment by shiftkey** [comment]
This behaviour might have changed recently, but the loading GIF should be scoped to the lifetime of the install action:

https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/Update/Program.cs#L100-L108

My guess is that your application is being invoked twice (the first time with `--squirrel-install` to indicate that the installation is complete, the second with `--squirrel-firstrun` to indicate this is your first run after the installation is done).

From the [docs](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/custom-squirrel-events-non-cs.md#application-startup-commands) about these events: 

> Exit as soon as you're finished setting up the app

Your Electron app should be aware of both events, but it should exit immediately after `--squirrel-install` is run rather than perform the default behaviour of displaying any UI.
