### ISSUE TITLE
Install error running Setup.exe with 1.7.6 only

### ISSUE THREAD

**Issue by DaneVinson** [Squirrel/Squirrel.Windows#1071]
As of 1.7.6 running Setup.exe throws the following error at the end.
![setup_fail](https://user-images.githubusercontent.com/3945597/27391836-dce8ca72-5659-11e7-91b9-b7f2cf44bfd4.png)
The application runs as expected after the error and the app's directory and file structure (in AppData\local) look correct. If I uninstall, roll back my Squirrel version to 1.7.5, releasify again and run setup again I no longer get the error. I'm attaching a SquirrelSetup.log file with has two setups in it. The first using 1.7.6 (error) and the second using 1.7.5. I don't see any differences. There are a few errors listed but they exist in both runs (and are what I've typically seen in all Squirrel installs in the past). I'm not sure how to debug this one.
[SquirrelSetup.log.txt](https://github.com/Squirrel/Squirrel.Windows/files/1091978/SquirrelSetup.log.txt)

**Comment by frederikolsen88** [comment]
I'm experiencing this as well, and I only noticed because I had an older solution to test Squirrel out with lying around, and this solution still used 1.7.5.

For reference, I've attached logs for the failing 1.7.6 installation and the working 1.7.5 installation. As Dane points out, they both contain the same Exceptions, though everything I've read about these indicates they're "only" warnings.

[SquirrelSetup_log__175.txt](https://github.com/Squirrel/Squirrel.Windows/files/1093980/SquirrelSetup_log__175.txt)
[SquirrelSetuplog__176.txt](https://github.com/Squirrel/Squirrel.Windows/files/1093981/SquirrelSetuplog__176.txt)

**Comment by JKSnd** [comment]
I'm also experiencing this with 1.7.6

On a windows 8 machine that I've been experimenting with I get an extra error report that hints at an ObjectDisposedException. The pop-up isn't very enlightening, unfortunately.
