### ISSUE TITLE
Broken shortcut - zero byte file

### ISSUE THREAD

**Issue by RichardD2** [Squirrel/Squirrel.Windows#1129]
I've created a basic WPF application, which does nothing more than display the assembly version number in the window.

I've followed the instructions from [Visual Studio Build Packaging](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/visual-studio-packaging.md), and built the application in Release mode. This generates the "Releases" folder under the project.

I run the `setup.exe` file from the releases folder, and the application starts. It creates a shortcut on the Start Menu and Desktop pointing to `%LocalAppData%\TestSquirrel\TestSquirrel.exe`, but that is a zero-byte file.

![squirrel](https://user-images.githubusercontent.com/2158265/29361281-cf15ab4e-827e-11e7-9a79-56b62180c5be.png)

![squirrel-2](https://user-images.githubusercontent.com/2158265/29361460-a2996a8c-827f-11e7-8f98-839a62f9470c.png)

Once the application has been closed, it is impossible to start it again from the shortcut. Windows complains that the shortcut is invalid, and suggests deleting it.

According to [Install Process](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/install-process.md), the shortcuts should be pointing to `update.exe`, passing the executable name as an argument. But that is clearly not the case here.

There are two previous reports of this issue:

* #1098 relates to a console application, which is not the case here.
* #1026 was caused by Avast, which I am not running. _(I'm using Windows Defender.)_

Am I missing something?

**Comment by RichardD2** [comment]
My project: [TestSquirrel.zip](https://github.com/Squirrel/Squirrel.Windows/files/1228041/TestSquirrel.zip)

**Comment by lukeskinner** [comment]
The shortcut using update.exe and passing the exe name is for versions before 1.5. Since 1.5 squirrel uses a stub exe for launching the application. So the shortcut pointing to ```%LocalAppData%\TestSquirrel\TestSquirrel.exe``` sounds correct as that path is where the stub should be.

I had a quick look at your project you uploaded. If you unzip the .exe installer, in the .nupkg within you should find a TestSquirrel_ExecutionStub.exe file in the lib\net45 folder. This file doesn't exist which is likely why you see a 0KB stub when you try to install it. 

Try following [this](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md):
1. Add the AssemblyInfo attribute
2. Add the SquirrelAwareApp.HandleEvents method to your startup code 

You shouldn't have to do the above but it might get you going. I can try debug the issue if not.

**Comment by RichardD2** [comment]
Thanks for the reply, but unfortunately that doesn't make any difference.

I've added:

    [assembly: AssemblyMetadata("SquirrelAwareVersion", "1")]

and changed the update method to:

    string path = ConfigurationManager.AppSettings["updatePath"];
    if (!string.IsNullOrEmpty(path))
    {
        try
        {
            using (var mgr = new UpdateManager(path))
            {
                SquirrelAwareApp.HandleEvents(
                    onInitialInstall: v => mgr.CreateShortcutForThisExe(),
                    onAppUpdate: v => mgr.CreateShortcutForThisExe(),
                    onAppUninstall: v => mgr.RemoveShortcutForThisExe());
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

But I still get a shortcut pointing to a zero-byte file. Opening the `nupkg` file with NuGet Package Explorer, there's no sign of a `TestSquirrel_ExecutionStub.exe` anywhere.

**Comment by RichardD2** [comment]
Updated project: [TestSquirrel.zip](https://github.com/Squirrel/Squirrel.Windows/files/1228210/TestSquirrel.zip)

**Comment by lukeskinner** [comment]
Code from the releasify process:
``` .Where(x => !x.Name.ToLowerInvariant().Contains("squirrel.exe"))```

After another look I can see Squirrel excludes it's own .exe from being used when creating the stub. It does this by doing a .Contains() on the file path. Your exe is TestSquirrel.exe so it gets excluded as it matches squirrel.exe. 

Try renaming the assembly name in the visual studio project settings i.e. TestApplication instead of TestSquirrel. 

I think this behaviour is technically a bug but it's unlikely any released applications are going to have squirrel in their assembly name.

**Comment by RichardD2** [comment]
Aha! I knew it had to be something simple! :)

Thanks for the speedy help.
