### ISSUE TITLE
Package signing

### ISSUE THREAD

**Issue by Trinitek** [Squirrel/Squirrel.Windows#1158]
Stemming from PR #1121 

If I understand HTTPS cert pinning correctly, that only aims to protect against SSL certificate impersonation. I am looking for a solution that would help guard against a situation in which a malicious actor gains access to my release server and uploads a tampered package. While I could examine the certificates for the executables in the package after it has been downloaded and unpacked, this is much more cumbersome as a Squirrel consumer.

As a solution to the lack of catalog creation utilities on Linux and macOS, it would be possible to take the PE stub approach taken to build Setup.exe and generate a list of SHA-1 file hashes, append it to the PE stub's resource section, and then apply the Authenticode signature to the resultant PE. The PE of course need not be a runnable executable; it will only serve as a catalog container.

**Comment by paulcbetts** [comment]
Yeah, so, Squirrel.Windows inherently doesn't try to solve this problem - if someone is smart enough to break into your server, they're probably smart enough to break into whatever server has the certificate. This is an intentional choice to balance between security and ease-of-use, HTTPS is our security boundary.

Adding certificate verification makes everything more complicated - for example, how do you change certificates once yours expires? What if you need to switch cert vendors? We would need to set up something like Apple's [Designated Requirements](https://developer.apple.com/library/content/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG6) to do this feature properly, and that's just Too Much.
