### ISSUE TITLE
Squirrel.Windows always creates uninstaller registry entry. When uninstall is run, nothing happens

### ISSUE THREAD

**Issue by craigmccauley** [Squirrel/Squirrel.Windows#1227]
I made my application Squirrel aware and added the Handle Events to the beginning of my winforms application.

In AssemblyInfo.vb

`<Assembly: AssemblyMetadata("SquirrelAwareVersion", "1")> `
At beginning of MainFormLoad

```
SquirrelAwareApp.HandleEvents( _
    onInitialInstall:=Sub() MyOnInitialInstall(),
    onAppUpdate:=Sub() MyOnAppUpdate(),
    onAppUninstall:=Sub() MyOnAppUninstall()
)
```
Methods in MainForm class

```
Private Sub MyOnInitialInstall()
    Using mgr As UpdateManager = New UpdateManager(GetEnvAppSetting("ReleaseDirectory"))
        mgr.CreateShortcutForThisExe()
    End Using
End Sub

Private Sub MyOnAppUpdate()
    Using mgr As UpdateManager = New UpdateManager(GetEnvAppSetting("ReleaseDirectory"))
        mgr.CreateShortcutForThisExe()
    End Using
End Sub
Private Sub MyOnAppUninstall()
    Using mgr As UpdateManager = New UpdateManager(GetEnvAppSetting("ReleaseDirectory"))
        mgr.RemoveShortcutForThisExe()
        mgr.FullUninstall()
        mgr.RemoveUninstallerRegistryEntry()
    End Using
End Sub
```
I would prefer to not have an uninstaller entry so I did not put the mgr.CreateUninstallerRegistryEntry() call in MyOnInitialInstall. However it gets created anyways.

The only thing that seems to work is the creation of the shortcut. (If I don't have the create shortcut code there it does not get created.) When I try to run the uninstaller from add remove programs nothing seems to occur.

Am I doing something wrong in how I'm implementing SquirrelAware? How can I not create or remove the registry entry?

**Comment by Logikgate** [comment]
The onInitialInstall hook is called **after** the application is already installed but before Squirrel writes the uninstaller registry entries. Reference the below code link, FullInstall is called and then CreateUninstallerRegistryEntry is called.  Within FullInstall is where the squirrel aware apps are invoked.

https://github.com/Squirrel/Squirrel.Windows/blob/2932c8db7394a7bba1cfa56c10fc7d4ab46b3c79/src/Update/Program.cs#L234

Since the squirrel aware apps are invoked prior to the registry entries getting written the only other way I can think of for you to remove the registry entries is to call RemoveUninstallerRegistryEntry each time your application is run. Make sure to catch any exceptions that might be thrown by this though, below is the implementation of it.

https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/src/Squirrel/UpdateManager.InstallHelpers.cs#L143

**Comment by craigmccauley** [comment]
Thank you so much Logikgate!

My final code ended up being the following.

```
Using mgr As UpdateManager = New UpdateManager(GetEnvAppSetting("ReleaseDirectory"))
	SquirrelAwareApp.HandleEvents( _
		onInitialInstall:=Sub() mgr.CreateShortcutForThisExe(),
		onAppUpdate:=Sub() mgr.CreateShortcutForThisExe(),
		onAppUninstall:=Sub() mgr.RemoveShortcutForThisExe()
	)

	'We have no means of checking if the registry Key exists
	'Swallow error
	Try
		mgr.RemoveUninstallerRegistryEntry()
	Catch
	End Try
End Using
```
