### ISSUE TITLE
Updater.exe extracted by Setup.exe does not get executed by original user

### ISSUE THREAD

**Issue by LucasBaizer** [Squirrel/Squirrel.Windows#1264]
I have a computer on a Windows active directory which, by default, blocks executable files which are not whitelisted, unless they are run by an administrator. When an administrator runs a Squirrel Setup.exe, it extracts the Updater.exe to %localappdata%\AppName. When this is run, it is not run as administrator like the original Setup.exe was. This makes it impossible to run Squirrel setup applications on this computer, and other computers which are configured this way.

**Comment by paulcbetts** [comment]
Yep, this is by-design, Squirrel cannot run as Administrator because it will write files that are no longer accessible by the current user.

**Comment by dealproc** [comment]
Is the administrator not able to do an install for all users using the MSI file instead?

**Comment by paulcbetts** [comment]
The MSI file won't help with this because it will set an executable to run in the context of a logged-in user, which will be blocked by OP's setup

**Comment by oinochoe** [comment]
@anaisbetts 
Hello, I am using electron-builder-squirrel-windows version 24, and I set the following settings in electron-builder settings to run electron with administrator privileges to create a folder.

```
...
"build": {
    "win" : {
        "target" : ["squirrel"],
        "requestedExecutionLevel": "requireAdministrator",
    }
}
.,..
```

When set up like this, squirrel will also be run as an administrator. Is it okay to run it like this?

The reason I ask is because I saw in your post that squirrel is not designed to be run as an administrator.
Right now, when I build and run Electron with these settings, UAC pops up, but it doesn't seem to be a big problem, so I'm asking.

**Comment by anaisbetts** [comment]
@oinochoe Electron-builder is a fork and is not supported here, file a bug with them

**Comment by oinochoe** [comment]
> @oinochoe Electron-builder is a fork and is not supported here, file a bug with them


@anaisbetts 
It's not a bug. I'm just curious.
There was no problem when I ran it, but you said squirrel should not be run as administrator.

Does this mean there is no guarantee?

**Comment by anaisbetts** [comment]
@oinochoe It cannot be run as Administrator. Electron-builder has changed the code in a broken way to halfway make it work

**Comment by oinochoe** [comment]
> @oinochoe It cannot be run as Administrator. Electron-builder has changed the code in a broken way to halfway make it work

Thanks for the reply.
Then, after I have sufficiently tested and used it, I will PR to electron-builder.
