### ISSUE TITLE
Loadbalanced Releases

### ISSUE THREAD

**Issue by ezmani** [Squirrel/Squirrel.Windows#1279]
I have a couple of questions related to --releasify. We would eventually have about 2700+ clients (WPF) downloading software from the "releasified" single server over port 80. The calls are somewhat staggered but our concern is that this could potentially overwhelm the single point of download.

1. Can we loadbalance the download server across multiple servers? 
2. when --releasify runs is the output server specific? In other words if we run --releasify against two different servers with the same nuget package will there be difference in the output?

Any help would be much appreciated!
Mani

**Comment by lukeskinner** [comment]
You should only run --releasify once in my opinion regardless of how many servers you have. The reason being Squirrel generates Deltas packages and then hashes the file which it then stores in the RELEASES file. If the two servers produce slightly different packages then you'll end up with two different streams of updates - you might get errors updating when you get mismatches. 

It also depends on how you are hosting your files.

### Cloud Storage
 If you host your releases on AWS S3 or Azure's blob storage then this problem is largely solved for you - they will handle the scaling for you. The only thing you need to do here is run --releasify on a pc/server you own and then upload the output to the cloud storage. 

### IIS (Windows)
If you host your files on IIS you would still run -releasify once on a seperate pc/server. Then once your ready to publish the update copy it onto the web server. I haven't really used the web farm feature in IIS much but you would just need to make sure that all web server instances are updated at the same time.

### Network folder (internal)
If you use a update path like '\\servername\app\RELEASES' then you shouldn't need to worry about scaling in most cases as it should hopefully be on the local network and not over the internet. 

As a separate note if you are delivering updates over the internet you should be using SSL/port 443 where possible.

**Comment by ezmani** [comment]
Luke thank you so much for your response! Very much appreciated!

Mani

**Comment by Inzanit** [comment]
I'm not entirely sure this is Squirrel related.

You releasify once, as @lukeskinner has pointed out, and what you do with it beyond there is outside of the scope of Squirrel. How you/users get to the `setup.exe` or updates is up to you.

It looks like you were satisfied with Luke's answer, so this could be closed. @shiftkey

**Comment by anaisbetts** [comment]
This is a year late but I'll write it in case someone stumbles upon it via Google - the best way to avoid this is to not set your update check to be on a super small interval - if it's "every 8hrs", your traffic gets amortized across the full 8 hrs (kinda, depending on your userbase's timezones), instead of in a super tight window.

That being said, if you're using delta updates and a CDN (or even a solid static file share like S3, Azure Blob Storage, or IIS serving in static mode), you won't ever come even close to hitting a problem.

**Comment by shiftkey** [comment]
I'm going to close this out as external to Squirrel.Windows - thanks for the extra insight @anaisbetts!
