### ISSUE TITLE
Run squirrel.exe from outside the Package Manager Console.

### ISSUE THREAD

**Issue by KentJohnsonW** [Squirrel/Squirrel.Windows#1292]
I'm trying to learn how to create an installer without using Visual Studio. I am currently trying to use the MyApp project from the squirrel docs. I got it working as the docs describe from the VS Package Manager Console, but in order to run it from command line I copied squirrel.exe to the project's base dir and tried to run it the same way but from cmd prompt "squirrel.exe --releasify MyApp.1.0.0.nupkg". However I get exceptions when running it that way. 
[SquirrelSetup.log](https://github.com/Squirrel/Squirrel.Windows/files/1939560/SquirrelSetup.log)
What do I need to do differently?

**Comment by paulcbetts** [comment]
>  in order to run it from command line I copied squirrel.exe to the project's base dir 

Squirrel.exe expects to be in the folder that NuGet installs it to, because it looks up its associated tools relative to its path. For a project that has Squirrel as a dependency you:

1. Clone the project
1. Build the project which will run NuGet Restore on the project and download Squirrel
1. Run Squirrel.exe from the `tools` directory
