### ISSUE TITLE
Automatic Staged rollout

### ISSUE THREAD

**Issue by lironbenyeda** [Squirrel/Squirrel.Windows#1378]
Hi,
Is it possible to release a new version with a limit on the number of users who can install it?
From what I understand, I need to manually edit the release file.. 
Please tell me that there is another way :)

**Comment by paulcbetts** [comment]
Yes, you manually edit the release file and set the limit as a percentage. It's really easy though, the RELEASES file is a really really simple text file

**Comment by lironbenyeda** [comment]
But I can not release a version without limitation .. Do you have a solution?

**Comment by paulcbetts** [comment]
I'm not sure I follow - what's your current publishing process?

**Comment by lironbenyeda** [comment]
When I release a new version, the RELEASES file gets updated and then the new version is available that instant.
I want to have the file immediately have the %% so that not all users (who have auto-updates turned on) will get the new version.

**Comment by paulcbetts** [comment]
Yeah, I get that, but how are you doing the uploading? It sounds like you just need to add a step to your release pipeline that concatenates " # 10%" on the end of the file

**Comment by lironbenyeda** [comment]
I'm using squirrel - - releasify command with target directory. The users checking this directory (using update manager).. I can't release new version without limitation because it will kill me if everyone will try to download the new version at the same time. So I need solution..

**Comment by hyprwave** [comment]
The problem is there are scenarios, like ours where the app in question is being used throughout the day. Which means no matter what timer is used, a lot of people will get the update.
And since we want a fast yet still controlled rollout, it would be nice to have the release immediately available to 10% of the users to help us perform a somewhat clean rollback, while also restriciting the bandwidth used, which is also a main concern for us.
I've provided a pull request to make this step part of Squirrel releasify in order to avoid manually copying the files over, and also making it an integrated step in the release workflow.

**Comment by paulcbetts** [comment]
@hyprwave Yep! Please read my previous reply, I think this will work for you.

**Comment by bddckr** [comment]
What Paul said - just edit your RELEASES file before you put it up on your storage used by the update checks.
