### ISSUE TITLE
How to suppress error message when installation has failed?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1381]
Hello,

I'm using the below code to run the Squirrel Setup.exe silently:
```
Process process = new Process();
ProcessStartInfo startInfo = new ProcessStartInfo();
process.StartInfo = startInfo;
startInfo.FileName = "Setup.exe";
startInfo.Arguments = string.Format("--silent");
process.Start();
process.WaitForExit();
```

The problem is that when the installation fails for some reason, I'm getting the below error message box although I'm using the --silent argument.
![squirrel setup error dialog](https://user-images.githubusercontent.com/20972612/45218873-09cbbe80-b277-11e8-9477-14fe0145f4f0.PNG)

Is there any way I can suppress that error message? Thanks.

**Comment by shiftkey** [comment]
The relevant message is here:

https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/Setup/UpdateRunner.cpp#L276-L280

I worry about hiding this away when the installer fails without alternatives, because that's helpful context the user should report to the application developer.

I'd be happy to talk about alternatives in a fresh issue, but for the moment I'm going to close this out.
