### ISSUE TITLE
Deltas mechanism

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1418]
Hello,

How does the Squirrel update mechanism works? Does it download the packages and the deltas or does it create them upon update?

Thanks.

Sissi Konsta

**Comment by shiftkey** [comment]
@SissiKonsta there's an overview of the update process in this document: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-process.md

And some details about the delta packages themselves: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/delta-packages.md

> Does it download the packages and the deltas or does it create them upon update?

My understanding is that Squirrel will generate the new package from the previous full package (if it has it locally) and the downloaded delta package. Otherwise it might just go straight to downloading the latest full package if that's more efficient.

**Comment by shiftkey** [comment]
Closing this out as the question has been answered.
