### ISSUE TITLE
Squirrel doesn't create shortcuts

### ISSUE THREAD

**Issue by SleepyBoyy** [Squirrel/Squirrel.Windows#1460]
Hello!
For some time Squirrel doesn't create any shortcuts anymore.
[This is the log](https://hastebin.com/amebomufil.coffeescript); interesting should be the lines 36ff.
I don't know what to do with these exceptions, my project is a wpf application with squirrel.windows 1.9.1, DeltaCompressionDotNet 1.1.0, Mono.Cecil 0.9.6.1, SharpCompress 0.17.1, Splat 1.6.2.
I haven't done any major changes to Squirrel except [this one](https://github.com/SleepyBoyy/DebloatWindows/blob/master/DebloatWindows/DebloatWindows/MainWindow.xaml.cs#L26); I had the problem before the modification, too.

**Comment by paulcbetts** [comment]
> I don't know what to do with these exceptions

Post them in the bug! With a stack trace!

**Comment by SleepyBoyy** [comment]
> > I don't know what to do with these exceptions
> 
> Post them in the bug! With a stack trace!

Ooops, sorry!
I accidentally wrote "This is the code" instead of "This is the log".
There is the whole log of Squirrel, I cannot really debut it, as it is external.

**Comment by paulcbetts** [comment]
Did you censor the word `<USERNAME>` or is that what it actually printed?

**Comment by paulcbetts** [comment]
```
2019-03-20 19:40:29> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\<USERNAME>\AppData\Local\DebloatWindows\app-1.0.0\DebloatWindows.exe: System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
```

Squirrel applications cannot require elevation

**Comment by SleepyBoyy** [comment]
How can I fix this then?

**Comment by paulcbetts** [comment]
The way that I would fix it is that I would make the application UI not require elevation, until the user hits the "Do It" button. Then instead of doing the registry changes directly, relaunch yourself as Administrator with a `--execute-actions` flag. If your app on startup sees this flag, it should just do the reg actions and exit immediately.

**Comment by SleepyBoyy** [comment]
Well, everything's worked before even with elevation. I don't know what caused Squirrel not to create shortcuts.
There is probably something wrong with Squirrel, I can imagine this error being caused by a new installation of WiX, as it depends on it afaik

**Comment by paulcbetts** [comment]
Fam, it's right there:

```
 System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
```

This is *intentionally designed this way*. Squirrel apps *can't require elevation on startup*.

**Comment by SleepyBoyy** [comment]
Well, thanks, but why would this be wanted my anyone?

**Comment by tjcwilk** [comment]
Hi,

Just dropping a note to mention that I would also really like the ability to run the squirrel setup.exe binary with elevated permissions. If i run it elevated manually it works great, but currently there is no way to make UAC automated (that I know of).

I do understand the desire for apps to run as a normal user from the AppData folder, but  my app by design requires elevated permissions to function.
