### ISSUE TITLE
Squirrel replacement

### ISSUE THREAD

**Issue by MattJeanes** [Squirrel/Squirrel.Windows#1466]
Since Squirrel is no longer maintained (really sad to hear by the way, great project!) what supported alternatives are there? This is more of a community question than an issue but figure other people may look here for the same answer.

**Comment by richieeeeeeee** [comment]
Good question... Any suggestions?

**Comment by yxw** [comment]
I would suggest **AutoUpdater.NET**:
https://github.com/ravibpatel/AutoUpdater.NET

**Comment by aaronstine** [comment]
My company would very much like to continue using squirrel. My understanding is that there are other commercial products like slack and discord which rely on  squirrel.windows.  Is it possible that one of those vendors will fork  this repo and continue maintaining it?

**Comment by MarshallOfSound** [comment]
@aaronstine I'd suggest subscribing to https://github.com/electron/electron/issues/17722

**Comment by yklykl530** [comment]
First of all, I am very grateful to the community for providing these very good technical solutions such as Electron and Squirrel, which provide us with a very good basic development environment and technical solutions.
Second, our company is also investigating Windows update plans recently. Especially for the enterprise IT system solution, it needs to be pre-installed under the administrator authority and upgraded under the user authority. Windows User Account Control (UAC) has always been a very troublesome problem. Squirrel helped us solve this problem, and [its solution is very simple and solves the problem](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md). We think this is a very good solution, simple but useful, especially in the case of updating this complex and important.
Finally, we hope to participate in community discussions and make the best decision for the future of Squirrel and Electron platform updates. Squirrel is really a good technology project, and we don't want the entire project to stop because of this maintenance adjustment. 
Thank you again.😁

**Comment by shiftkey** [comment]
I want to bring #1470 to your attention about potentially figuring out a way forward...

**Comment by musmuris** [comment]
I'd also point out that Microsoft use Squirrel to deploy Teams https://blog.thoughtstuff.co.uk/2017/04/under-the-hood-of-the-microsoft-teams-desktop-application/

**Comment by robmen** [comment]
Squirrel is not dead. 😄

**Comment by kodaniel** [comment]
> Squirrel is not dead. 😄

Well, it doesn't work since 2.0.0, it looks pretty dead to me.

**Comment by anaisbetts** [comment]
> Well, it doesn't work since 2.0.0, it looks pretty dead to me.

Care to elaborate?

**Comment by kodaniel** [comment]
> Care to elaborate?

Someone already elaborated, I have the same issue in .NET6: https://github.com/Squirrel/Squirrel.Windows/issues/1789

**Comment by caesay** [comment]
I maintain a [relatively active fork](https://github.com/clowd/Clowd.Squirrel) which has fixed all the major issues in this library here. dotnet/core related issues, performance, etc.

**Comment by kodaniel** [comment]
> I maintain a [relatively active fork](https://github.com/clowd/Clowd.Squirrel) which has fixed all the major issues in this library here. dotnet/core related issues, performance, etc.

I've already found this fork and using it, thanks :)

**Comment by madhaven** [comment]
@anaisbetts ,
Why exactly did Squirrel development stop ?

**Comment by nickhodge** [comment]
In my experience, owning and maintaining an open source project is rather a thankless job.

You get tired. The unneeded dramas. The cognitive dissonance of wanting to help yet not having the time; but blaming yourself for things not working.

And these projects are just one part of your life. Other things take priority.

As its open source, people who really care fork, fix, re-release.

Life goes on.

It's just words typed into a computer to make sand do magical things.
