### ISSUE TITLE
DEPRECATED, sad...

### ISSUE THREAD

**Issue by Lukkian** [Squirrel/Squirrel.Windows#1469]
So Squirrel.Windows came to an end. Sad.

I was especially sad because I was having a lot of difficulties with ClickOnce and in the search for alternatives I got to Squirrel.Windows earlier this year (2019).

And now that I've finally managed to master its nuances and put a prototype project working satisfactorily, I once again will have to search to another alternative.

So I decided to create this issue to declare my sadness, but also to thank the author and contributors of Squirrel.Windows for all the time invested in the project, unfortunately I arrived at a bad time, but it is impossible not to recognize the good work dedicated until today.

Now I take this opportunity to ask for help, someone could direct me to a path toward a way to update my application as simple and efficient as Squirrel.Windows?

Thanks.

**Comment by dealproc** [comment]
There is so much sadness about the deprecation of this library... maybe someone in this community could pick it up and continue its work?

**Comment by Lukkian** [comment]
I hope so.
Unfortunately I do not have the experience and knowledge required.

**Comment by stajs** [comment]
#1466

**Comment by aloneguid** [comment]
Do we know what was the reason for deprecating this project?

**Comment by frederikolsen88** [comment]
I can't claim enough expertise to take ownership, but consider me interested in contributing if someone is interested in picking up the work on a new fork.

I've no idea why the project was suddenly deprecated without warning, and I think it's a shame to lose all the great work. I've looked around for viable alternatives, but frankly, none seem to come close to the elegance of this solution. The delta package mechanism is a killer feature that we would be very sad to lose.

**Comment by kolorafa** [comment]
There are already a lot more people more skilled about this project than me, and they are most likely using it already, like:
https://github.com/riwo/Squirrel.Windows
https://github.com/bitdisaster/Squirrel.Windows

Also I'm a Linux user so I'm no help even for testing, but at least for me, what this project is missing is a way to donate or some bounty system to reward fixing/improving it :)

**Comment by aloneguid** [comment]
I don't want to sound negative, but donating has never worked for OSS to pay even for a day of developer's time in one year, it's pathetic, been through this many times. I think cloning and supporting it as a community is a better idea.

**Comment by aaronstine** [comment]
My company [Identifi](http://identifi.io) recently adopted Squirrel and would be willing to spend some of our dev time contributing to the project.

**Comment by JayBeavers** [comment]
Thank you @paulcbetts for all of your hard work over the years.  Your dedication has been admirable.

**Comment by paulcbetts** [comment]
Hey all, thanks for the kind words. Just to reassure folx, what's _here_ won't be going away by any means, nor will the NuGet package be deleted. Because Complicated Reasons involving GitHub the Company, I'm just no longer in a position where I can maintain it anymore, and nobody else from GitHub is stepping up to do it. While I maintained this project solo for a long time, at the end of the day it's owned by GitHub, not me personally. 

From a practical perspective, the fundamentals of Squirrel.Windows haven't really changed in quite some time, so if you're using it now and it's working for you, it will probably continue to do so

**Comment by RonaldZaZ** [comment]
Did paulcbetts just shape shifted into anaisbetts!?

**Comment by Lukkian** [comment]
@anaisbetts What happened to Paul?

**Comment by anaisbetts** [comment]
Hi! Around a year ago I realized that the overwhelming depression and anxiety I've been feeling more and more over the last decade, is because of gender dysphoria. And in order to treat that gender dysphoria, I decided to start transition back in September. Already, I feel _so_ much better than before.

So if you're wondering why my name and profile pic just changed uhhhhh, that's why! I wrote about it some more here if you're curious: https://blog.anaisbetts.org/new-game-plus.

(this is wholly unrelated to the events of Squirrel.Windows, it just happened that today was the day that I flipped a bunch of my accounts)

**Comment by bddckr** [comment]
Thank you Ana! For the hard work from day one, for the years of supporting this project and for being so passionate in ensuring Squirrel as a library had the user UX as one of the main important goals at all times!

I wish you all the best on any journey you're taking!

**Comment by Lukkian** [comment]
Of course Ana, I just asked because I was worried about you.
I wish you much success and good luck.

**Comment by RonaldZaZ** [comment]
Oh wait, it is the same person, I didn't notice that.
Anyway, good luck on your journey.

**Comment by shiftkey** [comment]
I want to bring #1470 to your attention about potentially figuring out a way forward...
