### ISSUE TITLE
Run an msi of dependency before/after installing the squirrel app

### ISSUE THREAD

**Issue by maheesuryal** [Squirrel/Squirrel.Windows#1495]
I am new to C# app development and Squirrel. I have a C# based application which needs another application to perform certain functionality. Both the apps were previously packaged into a single msi file to be given to the client. I have tried to use squirrel to perform auto-update on my main application. Is there any way by which I can pack both the packages in a single setup file using squirrel?

**Comment by Thieum** [comment]
@maheesuryal Do you want both apps to have auto-update capabilities, or just your main application?

**Comment by maheesuryal** [comment]
Just the main app.

**Comment by Thieum** [comment]
@maheesuryal Did you consider keeping the logic of installing the other app completely encapsulated in your main application? - you would have more freedom this way imho.
For example you could:
- check if the other app is installed (msi usually push a registry key)
- if not, download the msi (or using one shipped with the app if offline mode is needed?)
- install the msi
- check that no error has occured (return code, other checks)

This could be done before your main app ui starts. This would separate the concerns of installing your main app, and the other app, instead of trying to install both at the same time through squirrel custom events.

**Comment by maheesuryal** [comment]
That's a good idea. I'll try it out. Thanks a lot!

**Comment by maheesuryal** [comment]
The idea worked well. I am facing another issue now. If I uninstall my main app(the squirrel based one), the other application needs to be uninstalled too. Any ideas on how to solve this case?

**Comment by gojanpaolo** [comment]
Will including both the apps into a single .nupkg work? This would mimic your previous deployment:
> Both the apps were previously packaged into a single msi file

You can tell Squirrel to create desktop shortcuts for either one or both the apps. https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md#overriding-default-behaviors

**Comment by maheesuryal** [comment]
Yeah I have included both of them in the same nupkg file created shortcut for the main app and installed the other app from the main app. The issue arises here. When I uninstall my main app, I want my other app also to be uninstalled. Any help is appreciated.

**Comment by gojanpaolo** [comment]
Are you still creating a separate msi for the other app? What I meant was to just package both the apps' files (i.e. the other app's binary files instead of an msi) into a single Setup.exe generated by Squirrel. This way you don't need to add custom logic to install and uninstall the other app from your main app.

**Comment by maheesuryal** [comment]
The other app is a third-party app. I don't have the binary files of that application. Hence, I'm using its msi file to install.

**Comment by Thieum** [comment]
@maheesuryal you could try to use the Squirrel custom for uninstall as documented [here](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/custom-squirrel-events.md) and trigger the other app uninstall on this event.

**Comment by maheesuryal** [comment]
Thank you! I'll look into it. One more thing, is there any way by which I can prevent the user from quitting the application while the app is updating?

**Comment by Thieum** [comment]
@maheesuryal you can disable the UI, and/or open a blocking dialog while it is updating depending on the technology you are using. It will not prevent a user from killing the app through the task manager. Squirrel doesn't provide UI, but you can build one around the functionnality it provides.

**Comment by maheesuryal** [comment]
Thank you! One more thing, I'm currently hosting my squirrel app on a local http server. The app doesn't update inspite of giving the right url "http://localhost/Releases". When I point the update path to the local folder it works. Any idea why and how I can fix it?

**Comment by Thieum** [comment]
@maheesuryal if you are using iis, there is [doc about it ](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/microsoft-iis.md) that could help.

**Comment by maheesuryal** [comment]
That solved my problem. Thank you so much for you help @Thieum and @gojanpaolo

**Comment by Thieum** [comment]
@maheesuryal you're welcome! Feel free to close this issue - if anything else happens, you can open a new one.
