### ISSUE TITLE
Uninstall doesn't appear to be doing anything

### ISSUE THREAD

**Issue by Monbrey** [Squirrel/Squirrel.Windows#1565]
I don't seem to be able to manually uninstall the app - attempting to do so from either Programs and Feature or the new Apps interface just silently does nothing as far as I can tell.

Is there anything I need to implement in my app for this to work? I thought it would just remove all files from the AppData directory.

**Comment by anaisbetts** [comment]
You don't need to implement anything in your app, I would check the `%LocalAppData%\YOURAPP\SquirrelSetup.log` for a clue

**Comment by veevandyke** [comment]
Just wanted to comment here in case anyone else comes across this issue. I had the same problem, and discovered that it was due to an extra copy of update.exe in the app-* folder. 

Remove this from your nupkg and the uninstall works a treat again. Deleting it from the app-* folder manually does not seem to work. You need to delete your files, reinstall with an updated nupkg and reinstall. Once reinstalled, the uninstall works.
