### ISSUE TITLE
Using client certificate

### ISSUE THREAD

**Issue by FuzzyHagai** [Squirrel/Squirrel.Windows#1587]
Hi,

I am required to protect my updates server using client certificate. Is there a way to configure Squirrel.Windows to use client certificate when it accessed the remote server, or that feature needs to be developed?

Thanks!

**Comment by tkouba** [comment]
UpdateManager constructor has optional parameter IFileDownloader. Standard FileDownloader constructor has optional parameter WebClient, so you can create class

```csharp
class MyWebClient : WebClient
{
    protected override WebRequest GetWebRequest(Uri address)
    {
        HttpWebRequest request = (HttpWebRequest)base.GetWebRequest(address);
        request.ClientCertificates.Add(new X509Certificate()); // TODO: your certificate
        return request;
    }
}
```
and then
```csharp
var fileDownloader = new FileDownloader(new MyWebClient));

using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases", null, null, fileDownloader))
{
    await mgr.UpdateApp();
}
```
disclaimer: not tested

**Comment by ilnairb** [comment]
I tried this code but the UpdateApp() gave me the error "The underlying connection was closed: An unexpected error occurred on a send.".

**Comment by anaisbetts** [comment]
Squirrel does not support client certificates. That being said, you can come up with any kind of update scheme you want, here's an inefficient yet workable solution:

1. Fetch the RELEASES file yourself and validate the client certificate, save it to an empty directory
2. Download any .nupkg files that are higher than the current version to the same directory
3. Invoke Squirrel but use the directory rather than an HTTP URL as your update target
