### ISSUE TITLE
Security breach articles from a year ago - were they addressed?

### ISSUE THREAD

**Issue by Alonzzzo2** [Squirrel/Squirrel.Windows#1635]
Hi,
I started using Squirrel with our product a couple of weeks ago.
I only later found at that it isn't being actively maintained.., and now I found this article:
https://www.bleepingcomputer.com/news/security/microsoft-teams-can-be-used-to-download-and-run-malicious-packages/
There are a couple more articles on the same subject.
Were these issues addressed in previous commits?
Or is it still unsafe to use Squirrel as my installer?

Thanks!

**Comment by anaisbetts** [comment]
These security vulnerabilities are low priority at best, because they do not involve crossing a security boundary, only to evade a particular configuration that the vast majority of people do not run (and imho is an ineffective way to secure workstations). Anyone who can write arbitrary data to a user's profile is already Owned, they don't have to Trampoline off of Squirrel, they can just write themselves to Startup and they're already Done.
