### ISSUE TITLE
'Squirrel' could not be found on WPF .Net Core

### ISSUE THREAD

**Issue by Macaret** [Squirrel/Squirrel.Windows#1646]
I'm trying yo integrate Squirrel to a WPF project build with .Net Core 3.1. I'm using Visual Studio 2019.

The installation process works successfully with Package Console and Nuget, but when I'm trying to add the reference:

"using Squirrel;"

I'm getting The type or namespace "Squirrel" could not be found. 

I tried reinstalling, restarting, etc. Nothing seems to fix the issue.

**Comment by lars-29palms** [comment]
Hi, I was dealing with the same issue an hour ago :)
Using version 1.9.0 fixed the issue for me, see: [https://github.com/Squirrel/Squirrel.Windows/issues/1374#issuecomment-552361287](url)

**Comment by Macaret** [comment]
You are right. Thanks!

**Comment by lars-29palms** [comment]
@legistek I think it is using the existing installation of .NET Framework in that case. So if the project (in this case Squirrel) does not support .NET 5 or .NET Core it can still be used and deployed but relies on the target Framework being installed on the end user's computer

**Comment by legistek** [comment]
Oh I see. Thanks for that info. Unfortunately Releasify won't work properly with .NET5 assemblies though, so it doesn't appear I can use Squirrel at all. I'm moving onto MSIX. Shame, this was such a good installer.

**Comment by legistek** [comment]
Well, I really like Squirrel and have used it for 4 years for my wpf app. I'd prefer to keep using it over msix but have been forced to upgrade to .net5 at long last. Since I can't seem to get Squirrel working with it and it doesn't sound like there are any plans to make it work with .Net 5/6+ it doesn't seem like I have another option. 

But there are definitely things about MSIX I don't like. The sandbox thing makes me nervous. Will people have installation problems if they don't have developer mode? Seems like a remnant of Metro that won't die. Microsoft keeps changing its app ecosystem almost yearly so who knows if MSIX will even be a thing in a year or two. Also Squirrel is truly one click; MSIX is not. I can't add a desktop icon. Etc etc etc.

I could go on, but I'd really love if you guys just updated Squirrel to work with .net5+.  But I realize you're not making money off this so I cant blame you for moving on. I can just say thanks for what you did.

**Comment by robmen** [comment]
First, @anaisbetts did all the work and she deserves nearly all the credit (the rest of the credit goes to all that submitted features/fixes 👍🏻). I've barely gotten started. 

I share many of your concerns about MSIX and while I fully support it and MSI (via my work on the @wixtoolset), I wonder if there is a need for an independent installation engine that advances with the needs of developers. I've just started conversations with @anaisbetts about "Squirrel v3" and one very big question is: Do developers care enough about the installation engine to support its development... or is something like MSIX good enough?

There are some fixes around Squirrel v2 to better handle .NET 5 but it's slow going, a lot because there isn't an answer to the question above. I'm trying to build confidence before jumping into a Squirrel v3.

**Comment by nickhodge** [comment]
I love @anaisbetts work. When you look at Squirrel there are many moving parts that work together to make a superb auto-updating installation engine.

It have used it in a variety of products with great success -- once you get your head around the "devops" process.

These products are WPF / .NET Framework 4.7 related due to technical debt, use of lower-level Windows features.

There are downsides and technical "cliffs" that do concern me about the future of Squirrel and auto-updaters in general

- increasing security concerns: especially related to anti-virus tools thumbprinting Squirrel's entry .exe (possibility related to bad actors using Squirrel to do nefarious things?)
- Microsoft hardening and changing the operating system to stop background installers

I, like other commenters here, am confused about the desktop app installer strategy from Microsoft.

The core use-case for Squirrel is easy auto-update from an internet source.

What Microsoft endorsed product/service/format/standard is correct? Is it MSIX? Is it Winget? Is it the Store?

Or is the future PWAs? 

Unsurprisingly in the Microsoft world, it is all very opaque and noone knows nor can give a clear answer.

**Comment by legistek** [comment]
Sorry to drop off for awhile, got sidetracked.

Perhaps I'm doing something wrong but I'd really love to still be able to use Squirrel with my WPF .NET5 app, even if it's not the newest version of Squirrel. Can anyone confirm whether this is actually possible and if so provide step by step instructions? There seems to be a bit of confusion on this - at least on my part. :)  Thanks!

**Comment by legistek** [comment]
@AArnott thank you so much. After several weeks of having this in our dev environment everything is working fine and we'll be able to stick with Squirrel for the time being. Would love to see this in the official release. Thanks again!

**Comment by legistek** [comment]
Thought I should mention @AArnott's solution works great with .NET6 as well. Thanks again!

**Comment by user16307** [comment]
Hi all I try @AArnott's solution but when I run PM> Install-Package squirrel.windows -version 2.0.2-netcore , I get the error:

Restoring packages for C:\Users\h2so4\OneDrive\Documents\Visual Studio 2022\Projects\Extras\WpfTestGitSqu\WpfTestGitSqu\WpfTestGitSqu.csproj...
  GET https://api.nuget.org/v3-flatcontainer/squirrel.windows/index.json
  OK https://api.nuget.org/v3-flatcontainer/squirrel.windows/index.json 2829ms
Install-Package : NU1102: Unable to find package squirrel.windows with version (>= 2.0.2-netcore)
  - Found 76 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
At line:1 char:1
+ Install-Package squirrel.windows -version 2.0.2-netcore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'WpfTestGitSqu'.
At line:1 char:1
+ Install-Package squirrel.windows -version 2.0.2-netcore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by AArnott** [comment]
@user16307 Per my [comment above](https://github.com/Squirrel/Squirrel.Windows/issues/1646#issuecomment-950033842), you need to install the package from my feed -- not nuget.org, since it's not an official version.

**Comment by caesay** [comment]
[My fork is also fairly popular](https://github.com/clowd/Clowd.Squirrel) and supports .net 6/7 etc. Works both with self contained or framework dependent.
