### ISSUE TITLE
App Version, Exe and Config file not removed on uninstall

### ISSUE THREAD

**Issue by mhsimkin** [Squirrel/Squirrel.Windows#1694]
**Squirrel version(s)**
Squirrel version 2.0.1

**Description**
The same issue as in #1667.

When I uninstall the application the app-version# folder and the application exe and app.config are not removed.   I only have one exe in my application.  All the other files (dlls, resources, icons, etc.) are removed.

**Expected behavior**
app-version# folder, exe and config file should be removed.

**Actual behavior**
Files and folder are not removed.

**Additional information**
There is no log file available.

**Comment by vernou** [comment]
I have the same issue. After uninstall, this files are present in `%localappdata\AwesomeApp%` :

- app-1.0.0\Awesome.exe
- app-1.0.0\Utilitary.exe
- Update.exe
- .dead

**Comment by anaisbetts** [comment]
This is unfortunately not easily done, you cannot use `MOVEFILE_DELAY_UNTIL_REBOOT` unless you are UAC elevated. Your app EXE hanging around is most likely because you're not exiting properly when being run with `--squirrel-uninstall`, and the `.dead` file is important for machine-wide installations
