### ISSUE TITLE
Exodus Wallet Installation Failed

### ISSUE THREAD

**Issue by yahia-29** [Squirrel/Squirrel.Windows#1702]
trying to install exodus wallet on windows 10 64-bit .Net 4.5.3 but it keeps saying installation failed. 

and I got this log snippet 
![image](https://user-images.githubusercontent.com/78691387/107895298-8a5c7200-6f3b-11eb-8e7d-d337d491d935.png)

**Comment by anaisbetts** [comment]
This is not a user support forum, and your screenshot is completely unreadable (the section you have highlighted is a warning)

**Comment by Comp0sMentis** [comment]
haha this looks familiar... it looks like your flux capacitor needs to be chrono-synchronized with this dimension's ripple, idk how you're installing something 4 years ago but sometimes you gotta do stuff like that on Macs but not 64 bit windows, but I suppose there are always exceptions

**Comment by MFS05Maledixion** [comment]
@anaisbetts wow. The worst way to respond for real. This was a trashy response.
There are many folks with the same issue incase you did not know, if you're involved in the Exodus project, you should try to help as best as possible instead of saying talk to your vendor.  (github is open to discussions on issues about the projects there 😑)

You do realize windows users download the desktop wallet straight from Exodus themselves, so they are the vendors.
Don't answer like this next time, please, you come off as rude, running from something and just outright dumb.

Not good at all.

**Comment by anaisbetts** [comment]
I am not involved in the Exodus project. Also cryptocurrency is a stupid and a scam

**Comment by MFS05Maledixion** [comment]
marking my comment as disruptive? 😑

**Comment by MFS05Maledixion** [comment]
> @anaisbetts wow. The worst way to respond for real. This was a trashy response. There are many folks with the same issue incase you did not know, if you're involved in the Exodus project, you should try to help as best as possible instead of saying talk to your vendor. (github is open to discussions on issues about the projects there 😑)
> 
> You do realize windows users download the desktop wallet straight from Exodus themselves, so they are the vendors. Don't answer like this next time, please, you come off as rude, running from something and just outright dumb.
> 
> Not good at all.

Marking my comment as disruptive? 😑

**Comment by tankemo** [comment]
Anaisbetts, I get that this isn't an Exodus forum or project, But your response wasn't necessary. He didn't ask you for your opinion on Crypto; as you described it as 'Stupid and a Scam' - in fact you could have just said, sorry we can't help as this is an issue that needs to be resolved with Exodus. Please keep in mind how your word can impact others. I do hope this is and will be a teachable moment for you. take care!
