### ISSUE TITLE
simple sample request

### ISSUE THREAD

**Issue by ghiboz** [Squirrel/Squirrel.Windows#173]
hi all!
it's possible see a simple sample to manage correctly the request to check if there are downloads available and the update process?

thanks

**Comment by dealproc** [comment]
working on it, @ghiboz ... well.. i'm working on a full deployment pipeline.  having a few issues that i've reported, but it looks like this:

https://github.com/dealproc/squirrel-poc/blob/develop/source/ClientApp.WinHost/MainWindow.xaml.cs

I seem to have found a glitch in the update system (with a bug filed) that you want your package id for the nuget package to not contain any periods in it.

HTH

**Comment by GeertvanHorrik** [comment]
We created this package so we can embed squirrel in all our apps:

https://github.com/WildGums/Orc.Squirrel/blob/develop/src/Orc.Squirrel/Services/UpdateService.cs

It supports:

1) Several channels (for example, beta and stable)
2) Check if the update system is even available (does update.exe exist or is it a manual install (we also support offline installers in program files))
3) Updates installed events
4) Updates outside maintenance window

Note that we have a manual build because:

1) Our version of Squirrel supports semver
2) Out version of Squirrel supports exit codes and maintenance windows (it adds release dates to the RELEASES file)

**Comment by ghiboz** [comment]
thanks @GeertvanHorrik !
very interesting :)

**Comment by Inzanit** [comment]
This looks like it's been resolved? @shiftkey
