### ISSUE TITLE
Marked as malware by MalwareBytes?

### ISSUE THREAD

**Issue by tiagozip** [Squirrel/Squirrel.Windows#1875]
I recently scanned my laptop using Malwarebytes and noticed some files for Squirrel.Windows were being detected as malware. These files were installed by Electron (official release) when I was testing the installer creation of my app, so I don't think they should be malware. The flagged files were squirrel.exe (in app_data/local/electron_app_name/version/squirrel.exe) and update.exe (in app_data/local/electron_app_name/update.exe).

I'm not sure if this is related to Squirrel.Windows itself, but I thought it was worth posting because the MalwareBytes forum isn't working for me.

```
<log removed>
```

**Comment by anaisbetts** [comment]
Ask the developer of this Electron app to sign the app, this will help. Otherwise, there's not much we can do, they have not detected a specific virus here, they have detected a "heuristic" where they think that Squirrel is acting like malware because it installs software (but unlike malware, it is done with user consent!)

**Comment by tiagozip** [comment]
Oh ok, thank you. I was making the app myself and didn't really know that any exe that installs other file could be detected.
