### ISSUE TITLE
What are top couple of challenges with ClickOnce that led you to develop Squirrel?

### ISSUE THREAD

**Issue by pisees** [Squirrel/Squirrel.Windows#242]
It looks like you may have used ClickOnce in GitHub for Windows.

Thanks,

**Comment by pisees** [comment]
I do se this twitter that GitHub for Windows did use ClickOnce, and that developing Shimmer, which I believe has evolved into Squirrel: https://twitter.com/paulcbetts/status/248653717560246273

**Comment by smourier** [comment]
I'm interested by that question too. I think Squirrel is attractive but what does it solves exactly (apart from the native app support and the non configurable setup look, say)? no UAC, no reboots, dependencies, etc is already in clickonce AFAIK (and that's actually why it's not suited for enterprise setups as you are discussing in other issues).

**Comment by shiftkey** [comment]
A couple of blockers that (from what I understand) won't be fixed in ClickOnce:

- Standalone installer - no dependency on network after downloading
- Proxy server issues with installation
- Transforming a 32-bit app to a 32/64-bit app is not possible without uninstalling the old app

For reference, [Visual Studio Code](https://code.visualstudio.com) uses Squirrel under the hood for their installation and updates.

**Comment by flagbug** [comment]
Also, you can change the update server URL, which isn't possible with ClickOnce
