### ISSUE TITLE
If a new release comes with a newer version of Squirrel, which Update.exe runs when updating?

### ISSUE THREAD

**Issue by theofanis** [Squirrel/Squirrel.Windows#302]
What the title says.

Version 1 has Squirrel x and version 2 has Squirrel y. When version 1 checks for update and installs the update, which Squirrel version runs?

If x is running to update the app, then it probably misses some fixes.

**Comment by sandyarmstrong** [comment]
Pretty sure all the update code runs in the app itself, therefore it would be using Squirrel x. Right?

**Comment by paulcbetts** [comment]
@sandyarmstrong It depends - Squirrel kind of has two modes of operation - one for C# apps where Squirrel code is running in the context of the app itself, and one for non-C# apps, where Update.exe ends up being the "public interface" to the Squirrel API (which is why its list of command-line switches is insanely long).

Anyways, to answer the original question, the original version of Squirrel runs the entire update process in both cases :(

**Comment by Thieum** [comment]
@shiftkey original question anwered, this can be closed.
