### ISSUE TITLE
Squirrel should not throw "Exception"

### ISSUE THREAD

**Issue by bgrainger** [Squirrel/Squirrel.Windows#306]
There are a number of places in the Squirrel code that [`throw new Exception`](https://github.com/Squirrel/Squirrel.Windows/search?utf8=%E2%9C%93&q=%22throw+new+Exception%22).

This frustrates me as a consumer, because the only way I can handle them is `catch (Exception)`, which might catch legitimate exceptions thrown by my code (due to my bugs) and not just Squirrel errors. It also violates the *Framework Design Guidelines* (cf. [MSDN](https://msdn.microsoft.com/en-us/library/ms229007.aspx)).

I'd be happy to submit a PR to change these (would have to evaluate on a case-by-case basis; maybe some could become `InvalidOperationException` or `ApplicationException`, or maybe a new `SquirrelException` class needs to be introduced?) but wanted to open this issue for feedback first before changing the code.

Any preference on if or how you'd like this to be addressed?

**Comment by paulcbetts** [comment]
I don't really want to change this, sorry. Since we're not going to put contracts / documented guarantees around what kinds of exceptions every single method can throw (since doing so would effectively mean every method would itself have to be wrapped in dozens of try/catches so framework exceptions don't escape out), this means that when you're catching XYZException you're really just coding to the internals of what Squirrel _happens_ to do at the moment.

Because we don't have a contract of what exceptions are thrown, you _should_ `catch (Exception)` if you want to handle "errors thrown by Squirrel"
