### ISSUE TITLE
Specify required .NET version

### ISSUE THREAD

**Issue by stirno** [Squirrel/Squirrel.Windows#341]
Due to some updates in one of our dependencies (Roslyn, specifically) we're looking at having to start targeting .NET 4.6 in the near future (possibly even the RC version).

Just wanted to get an issue posted to start a discussion about if/how squirrel might deal with this.

**Comment by paulcbetts** [comment]
The way we'd probably deal with it is via another Squirrel attribute in your EXE - we can scan all of those, use that to write an entry in the VS_VERSION_INFO block with the required .NET version, then load it in Setup.exe. So the steps would be something like:

1. Create a new `[SquirrelMinimumNetVersion]` attribute
1. Rig Releasify to scan all the EXEs looking for that attribute (similar to what we do for SquirrelAware attribute), and take the highest number
1. In Releasify, use _something_ (RCEdit.exe?) to create the new RC entry
1. In Setup.exe, instead of using our hardcoded constant, go looking for the RC entry

**Comment by automatonic** [comment]
Lets see if I am understanding this correctly:

1. Modern versions of Windows can see what .net framework version is required (by interrogating the exe resources) and then automatically download/install the required version (if missing)
2. Squirrel for windows gets a new assembly-level attribute that an application can add to indicate the requred version (to squirrel for windows).
3. Releasify gets adapted to find the attribute in 2. and then set the exe resources to take advantage of 1. 

Is that correct? I assume there is no "framework bootstrapping" in squirrel for windows because of 1. Or did i miss something?

(I, too, am eyeing .net 4.6 for an upcoming release)

**Comment by jochenvangasse** [comment]
Any progress on this?
Otherwise I'd love to get started on a PR ;-)

**Comment by chizran** [comment]
Has there been any progress on this?

**Comment by paulcbetts** [comment]
@chizran Nope! I'd take a very thoughtfully written PR to add this though

**Comment by sickboy** [comment]
I've got a .NET461 branch and also electron-winstaller variant here:
https://github.com/sickboy/Squirrel.Windows/tree/net461
https://github.com/sickboy/windows-installer

**Comment by plinehan** [comment]
Can this be marked as closed?  #940 is now included in the released versions of Squirrel.

**Comment by Thieum** [comment]
@shiftkey fixed with #940
