### ISSUE TITLE
Nuget.core version is 2.8.60318.667 in 0.99

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#351]
As indicated in issue #350, the nugget.core version is now 2.8.60318.667. What appears to have happened is that the dependencies have been updated but the dependency requirements in the nuget package have not been updated (this also applies to splat and mono.cecil).

The problem that I discovered was that I was getting error reports like this:
Exception]:[System.IO.FileLoadException: Could not load file or assembly 'NuGet.Core, Version=2.8.60318.667, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: 'NuGet.Core, Version=2.8.60318.667, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Because the nuget package for nugget.core had not been updated to the same as the version used by squrriel.  Once I updated that and splat and mono.cecil updates work. The problem that I have is that there are some versions out in the wild where updates aren't working because they have the old nugget.core that is not the same as the version used by squrriel.  Is there any way around this?

Thanks,
Stefan

**Comment by paulcbetts** [comment]
Fixed

**Comment by simonz05** [comment]
I dont think this issue is solved:

"Because the nuget package for nugget.core had not been updated to the same as the version used by squrriel. Once I updated that and splat and mono.cecil updates work. The problem that I have is that there are some versions out in the wild where updates aren't working because they have the old nugget.core that is not the same as the version used by squrriel. Is there any way around this?"
