### ISSUE TITLE
Add ability to launch custom UI and run arbitrary code at Install time.

### ISSUE THREAD

**Issue by xavierzwirtz** [Squirrel/Squirrel.Windows#415]
I would like to be able to have an assembly compiled into the Setup.exe that contains custom UI and install logic. The facility provided by executing the app after install is not enough, I need to ask questions from the user during the install process. Basicly, a wizard :wink:

**Comment by paulcbetts** [comment]
Sorry, this will never happen! The only thing you can do in a Squirrel install is run your app. If your app is a Squirrel-aware app though, when your app is launched for the first time you'll get a special `--squirrel-firstrun` parameter which will tell that you can select some options.

**Comment by burgil** [comment]
Just a little UI that's all we're asking lol? Any successful alternative to Squirrel?

**Comment by iTrooz** [comment]
I understand that you do not want to bake an install UI (wizard) into squirrel itself because of its philosophy, but why not allow your users to do it themselves ? Shouldn't a user-provided function at install-time be able to achieve that, without too much trouble on your end ?

I cannot use Squirrel for my project without this feature, but I don't know any good alternative :/
