### ISSUE TITLE
Roaming Profiles

### ISSUE THREAD

**Issue by AndyStewart** [Squirrel/Squirrel.Windows#481]
Hi

First off this seems like a really great solution and thanks for open sourcing it. 

I need to install into an environment where they IT department destroy's the <USER PROFILE>\AppData\Local\Apps) folder on log off. They have suggested installing into the roaming folder instead, this doesn't sound like the right solution to me. Does squirrel have an answer to work around this issue or will the machine wide msi solve the problem? It looks like the machine wide msi just installs the installer into program files and not the actual application, which I'm not sure solves the issue as the user still has to install the application on every login.

Thanks for your help in advance.

Andy

**Comment by paulcbetts** [comment]
The Machine-wide installer would indeed solve your problem, though it would have a few odd side-effects, in that every time a user logs in, the app gets reinstalled (which in effect probably wouldn't be _so_ bad depending on your app).

Another solution you can do is block running EXEs from LocalAppData entirely via GP (i.e. follow the "Protect against CryptoLocker" guides online), which would force Squirrel to install into C:\ProgramData instead. If you have a choice though and it works, I'd just let it reinstall every time, it won't get in the way of the user's work since it's a silent install

**Comment by AndyStewart** [comment]
Thanks Paul, Thats excellent I've just found the details on how the msi's work in the release notes. The documentation is a bit thin on the ground around there, would you like a pull request that pulls that information into main documentation?

**Comment by paulcbetts** [comment]
:+1:

**Comment by Inzanit** [comment]
Looks like this is resolved @shiftkey
