### ISSUE TITLE
Create shortcut's icon using the app.ico instead of the executable.

### ISSUE THREAD

**Issue by lipis** [Squirrel/Squirrel.Windows#492]
At the moment when the shortcut is being created the icon is taken from the executable of the app.
![screen shot 2015-11-11 at 14 02 02](https://cloud.githubusercontent.com/assets/125676/11091651/e537a236-887c-11e5-8988-123fd53540f6.png)

But after a few updates (even though the shortcut should be updated on Desktop, Taskbar, etc) sometimes is not. It works OK even if the `Start in` points to a wrong direction but the disappearing icon is quite an issue. 

So if we would create the shortcut and choosing the `app.ico` instead the problem would be solved.

**Comment by paulcbetts** [comment]
> So if we would create the shortcut and choosing the app.ico instead the problem would be solved.

This isn't possible because you could ship >1 EXE file in your package. I'd rather just Fix The Bug of the icon not getting updated when we run updates

**Comment by lipis** [comment]
Fair enough.. at the moment in order to make sure that the shortcut is updated in the Pinned folder when updating/installing the app:

- Creating/updating the shortcut in the start menu
- Copying that shortcut into the Pinned folder (if it exists already there)

Fixing the bug would be golden though.. so I'm closing this one.

**Comment by tafs7** [comment]
I know this issue is old and closed, but I'm not clear on whether it was resolved.

I've installed my app using the machine-wide MSI.  Logged out, then logged back in, I see the desktop shortcut that is created, however the icon of the shortcut is the generic windows EXE one, even though I do include an app.icon in the directory of the release in %appdata%.
![image](https://user-images.githubusercontent.com/671795/27142490-d4653c96-50f0-11e7-86a8-045c47a925d1.png)

When I right-click the shortcut, and click "Change Icon...", i get the same behavior as the OP - Windows looks for an app icon resource embedded in the EXE, which is not where the app.ico file is.

What is the correct/expected behavior when you create the app release with a nuget pkg that contains a URL to an app icon file? Should it not use to embed into the EXE so Windows is happy and shortcuts work?  If not, please explain (or better, update the docs to clarify).

Thanks!
