### ISSUE TITLE
replace functionality of clickonce CurrentDeployment.ActivationUri

### ISSUE THREAD

**Issue by smadep** [Squirrel/Squirrel.Windows#565]
We are providing some app on 4 different servers with clickonce distinguishing the server the app needs to communicate with through that CurrentDeployment.ActivationUri parameter. 
So, user downloading app from server A would use the app communicating with server A, ...

We would like to move to Squirrel but need to keep that kind of functionality, to also provide only one version of squirrel package and not four.

Do you have any solution for that in mind?

Thx.

**Comment by paulcbetts** [comment]
Doesn't work, sorry. The only reason Microsoft can do this is because they cheat and include a piece of ClickOnce in-box with Windows.

Since NuGet packages are Just Zip Files, I'd write some scripts to edit the contents for servers A-D individually, then regenerate the RELEASES file (it's very easy to parse and recreate)
