### ISSUE TITLE
Is it possible to make setup.exe not roll back to a previous version?

### ISSUE THREAD

**Issue by MatthewSteeples** [Squirrel/Squirrel.Windows#584]
Back in the days of ClickOnce we could ship a single setup.exe file and it would always pull the latest version from the servers when installed and then ClickOnce would keep that up to date for us. Is the same possible with Squirrel?

If it's not possible, would it be possible to make it so that setup.exe doesn't nuke the currently installed version and re-install it's own version? Eg make it run the version that is already installed if it detects that it's newer.

**Comment by paulcbetts** [comment]
> Back in the days of ClickOnce we could ship a single setup.exe file and it would always pull the latest version from the servers when installed and then ClickOnce would keep that up to date for us. Is the same possible with Squirrel?

Nope, not at the moment. I really want to keep the initial install code path as fool-proof as possible. When install fails, users don't get to use the app at all, so anything making that possibility more likely is Bad

> If it's not possible, would it be possible to make it so that setup.exe doesn't nuke the currently installed version and re-install it's own version? 

This behavior is actually by-design, because it made life easier for our support people to deal with corrupt installs.
