### ISSUE TITLE
Support for tools NuGet packages

### ISSUE THREAD

**Issue by daveaglick** [Squirrel/Squirrel.Windows#680]
Would you consider support for pulling files from the `/tools` folder in the nupkg? Using `lib/net45` for executables and regardless of actual framework gives me the willies. More importantly, NuGet already understands the `/tools` folder as containing executables which means there would be better interoperability with other package consumers that expect this convention for sets of executables like Cake. I.e., we wouldn't have to make the package be Squirrel-specific and could just reuse an existing tools package.

I don't mind taking a look at this and submitting a PR. I could use a little guidance on where in the code to look for the hard coding of `lib/net45` though. Or perhaps there are reasons I don't understand why this was already considered and rejected...

**Comment by shiftkey** [comment]
I'm going to close this out because I don't want to bake more NuGet-specific functionality into these packages without better motivation. At the time the `nupkg` wasn't chosen with the intent of being a part of the broader NuGet ecosystem, it was just a familiar packaging format that worked nicely with other ZIP tools. It might even predate the `/tools` directory convention, but don't quote me on that.

We also have enough headaches with compressing/decompressing `nupkg` files in the wild that I'd prefer to tackle before looking at other things. Our NuGet fork is based on v2 and I'm not sure how much customization has been done that might be future nightmares for us.

**Comment by daveaglick** [comment]
👍 I had totally forgotten about this anyway. Do your thing.
