### ISSUE TITLE
Should Setup.exe just launch the already installed version if it's the latest?

### ISSUE THREAD

**Issue by KirillOsenkov** [Squirrel/Squirrel.Windows#693]
As far as I can understand Setup.exe produced by Squirrel blows away the entire %LocalAppData%\MyApp folder and reinstalls the app from scratch.

In case the exact version baked into Setup.exe is already installed in the MyApp folder, should Setup.exe just leave it alone and launch that? 

Maybe it should also first verify the SHA of the files and if they match what's in the .nupkg just run the app. If there's a mismatch (some file missing or corrupt), do what it does currently, e.g. delete the entire folder and install fresh.

This way one can use Setup.exe as a launcher (web-shortcut)?

**Comment by paulcbetts** [comment]
This is the way that Squirrel was actually originally designed, but we found at Slack that the vast majority of people rerun Setup because they're having some kind of problem - their app doesn't run, is doing something weird, etc etc. The thing that works the best for them in practice is to try to clean install from scratch

**Comment by KirillOsenkov** [comment]
Makes sense, thanks!
