### ISSUE TITLE
Question: Autoupdate and signed code

### ISSUE THREAD

**Issue by TheMSB** [Squirrel/Squirrel.Windows#755]
By reading the provided documentation I have not been able to discern how the autoupdate behaves when updates are not code signed.

In the event that the GitHub repository that hosts the updates for my application becomes compromised, will malicious third parties be able to serve code that autoupdate will just install without verifying a signature?

If the answer to the previous question is yes: Are there ways for me to prevent such a scenario? The exercise of code signing on Windows seems pointless if at any point third parties can inject code into my update process.

**Comment by engdata** [comment]
You can separately download and apply the update packages, so you could validate the package signature on your own.

**Comment by paulcbetts** [comment]
Code signing isn't used for validation, we use HTTPS to guarantee that the target we're talking to is who we think it is. If you host itself is compromised, Squirrel doesn't protect you out of the box for that. But, as @engdata says, since Squirrel splits apart downloads and application of updates, you can verify updates yourself using any means you choose.
