### ISSUE TITLE
Add quotes to 'version' argument in install\uninstall\update\obsolete\firstrun hooks

### ISSUE THREAD

**Issue by maximpashuk** [Squirrel/Squirrel.Windows#779]
I am trying to integrate Squirrel.Windows and Topshelf (https://github.com/Topshelf/Topshelf)

Everything is fine except passing 'version' commandline argument in Squirrel hooks.

When Squirrel calls install hooks on Topshelf, 'version' commandline argument passed as-is, without any quotes.

Example:
https://github.com/Squirrel/Squirrel.Windows/blob/c699425abc0f808de764de874b46cbdb7195db4c/src/Squirrel/UpdateManager.ApplyReleases.cs#L116

Topshelf command line parser expects that command line arguments are escaped with double quotes

Examples:
https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf.Tests/CommandLine_Specs.cs#L67

So I think it is fine for squirrel to explicitly escape commandline arguments with double quotes.
This will able topshel to parse version correctly.
I think this should not break up compatibility, since any commandline parser should support double quotes in arguments to escape whitespaces.

So please add double quotes to 'version' parameter in all Squirrel hooks.

**Comment by shiftkey** [comment]
> I think this should not break up compatibility, since any commandline parser should support double quotes in arguments to escape whitespaces.

I worry about breaking existing users in the wild who have rolled their own parser and baked their own assumptions about what Squirrel sends them.

It looks like TopShelf added support for this relaxed command line parsing, so I'm going to close this out as resolved because I worry this change (despite being good and right) would impact and break existing apps using Squirrel.
