### ISSUE TITLE
Possible to update scripts, scheduled tasks, and copy / replace files via Squirrel?

### ISSUE THREAD

**Issue by provkristian** [Squirrel/Squirrel.Windows#784]
Hello,
I have a question.  Is it possible to update scripts, scheduled tasks, and copy / replace files via Squirrel?  Or would one need to create a separate Squirrel aware app to be an updater like how Chrome uses a separate updater that presumable runs with some sort of admin credential?  Thanks.

Kristian

**Comment by sickboy** [comment]
I suppose you'd handle this in your squirrel aware app, you could relaunch itself with admin rights, and e.g a special CLI flag: --perform-some-action, so that the app behaves specifically for that use case, and terminates.
Careful though as iirc there are timeouts set for running Squirrel actions like Install shortcut, Uninstall, etc.

**Comment by paulcbetts** [comment]
You can't do anything involving UAC which unfortunately includes scheduled tasks (even for your own user!)   You should update files in your squirrel aware app

**Comment by kristianjaeger** [comment]
Thanks for answering.  Cheers.
