### ISSUE TITLE
Using .MSI nothing's happening 

### ISSUE THREAD

**Issue by SumitSharma1005** [Squirrel/Squirrel.Windows#851]
Nothing's happening by clicking **.msi**, But using **Setup.exe** able to install the app.
Can you please help me to figure out what exactly I am missing?

**Comment by hvassbotn** [comment]
See this case https://github.com/Squirrel/Squirrel.Windows/issues/555

**Comment by paulcbetts** [comment]
This is almost always because you:

1. Installed the normal EXE
2. Uninstalled it
3. Installed the MSI
4. Squirrel saw that the current user uninstalled the app and is respecting their wishes to not reinstall it

To resolve this, go into `%LocalAppData%` and delete your app's folder completely. If this isn't your bug, please reopen!
