### ISSUE TITLE
ICSharpCode.SharpZipLib.dll as a nuget dependency 

### ISSUE THREAD

**Issue by tankbob** [Squirrel/Squirrel.Windows#853]
Because this is being referenced directly without a public key token I have a conflict when using the NPOI package that depends on SharpLib that has the library with a public key token.

Could this be included as dependency instead, or if it is a custom patched version, could it not be done as a new assembly with different namespace to prevent conflicts.

**Comment by paulcbetts** [comment]
Our SharpZipLib is a modified version, though if I can get it to work, I'd like to kill this dependency altogether and move to SharpCompress

**Comment by dennismi** [comment]
please hurry, we have a dependency error with another vendor which we can not resolve at the moment. They do not like the version you have included. :( 

Am working with them to see if we can get it sorted with them.

**Comment by hatton** [comment]
This just cost me a lot of time, thinking I was going insane. The version checked in _doesn't even have a different version number_ from the one available on nuget. That's just cruel.

**Comment by hatton** [comment]
Here's what I see:

May 2010, SharpZip AssemblyInfo.cs has 0.86.0.518.

Sep 4, 2015, in c9a618c499cbea1cbdb8b24b0f25e58b67232f9a you pulled in SharpZipLib at https://github.com/icsharpcode/SharpZipLib/commit/e01215507cf25a5978a0bd850c9e67dbabf515b7 where we had fixed the directory separators on Linux/Mac.  Five years later, SharpZip AssemblyInfo.cs still has 0.86.0.518.

There are several releases on Nuget; the icsharpcode one there is also 0.86.0.518, from 2011. So indeed, we don't want to be using that one, it does lack the Linux/Mac fix.

**Comment by CBenghi** [comment]
Hello @paulcbetts,
I can't find a way out of this problem for my installer of https://github.com/xBimTeam/XbimWindowsUI. 
I've seen your branch replacing it with SharpCompress, have you got a clear todo on that front? 
If so I'm happy to help.
Claudio

**Comment by CBenghi** [comment]
Hello All,
since I could not remove sharpziplib from my app because of dependencies I've had to go for a more comlpex solution.
I've re-build and re-package Squirrel with a new version of sharpziplib. It seems to have worked for me.
I've used the latest version of SharpZipLib from jetbrains, I hope this includes the patch that squirrel needs.

Steps: 
A) In the squirrel codebase:
1 - Remove the direct link to the dll
2 - install SharpZipLib.JetBrains.Stripped from nuget.
3- repackage squirrel.nupkg in a local folder (I've given it a pre-release version past the current stable i.e. squirrel.windows 1.5.3-cb)

B) in your codebase:
4 - Install your version of  squirrel.nupkg from the local folder

This seemed to work well for me. But I did not have much time to test extensively.

If you want to skip 1, 2 and 3 I've placed the nupkg in our beta repository, you'll have to add
https://www.myget.org/F/xbim-develop/api/v2 to your nuget sources and download it from there.

I hope this helps.
Claudio

**Comment by GKBelmonte** [comment]
oh wow ouch...

**Comment by paulcbetts** [comment]
We replaced SharpZipLib a long time ago. Closing!

**Comment by GKBelmonte** [comment]
Cool stuff issue link? Version? tx!
