### ISSUE TITLE
Squirrel version/rollback solutions

### ISSUE THREAD

**Issue by markgould** [Squirrel/Squirrel.Windows#964]
Didn't know where to put this but I thought I'd share a solution I came up with that addresses some of the headaches of rollback/pre-release tags in versions

We use Octopus Deploy to deploy some of our software products to customers servers (and then invoke squirrel on the server) and this works great with a couple of caveats.  The main pain points are pre-release packages and rolling back. Both of these are solved by just creating a new Octopus release with new version each time, but this makes it hard to track on the dashboard what version any given customer might be on.

The absurdly simple solution I came up with today, is to simply increment the last release number. It's a little overkill but I quickly hacked this together:

```
function Get-NextVersionNumber {
    # parameters
    param ([string] $ReleasePath)

    $ReleaseFile = [System.IO.Path]::Combine($ReleasePath, "RELEASES")

    if ([System.IO.File]::Exists($ReleaseFile) -eq $false) {
        return "0.0.1"
    }

    $Lines = [System.IO.File]::ReadAllLines($ReleaseFile);

    if ($Lines.Count -eq 0) {
        return "0.0.1"
    }

    $LastLine = $Lines[$Lines.Count-1]

    if ($LastLine -cmatch '^([0-9a-fA-F]{40})\s+(\S+)\s+(\d+)[\r]*$') {
	    $result = $matches[2] -creplace '(-full|-delta)?\.nupkg$', ''
        if ($result -cmatch '\d+(\.\d+){0,3}(-[A-Za-z][0-9A-Za-z-]*)?') {
            $split = $matches[0].Split(".");            
            $split[$split.Count-1] = ($split[$split.Count-1] -as [int])+1
            return [string]::Join(".", $split)
        }
    }

    return "0.0.1";     
}
```

I can then call Get-NextVersionNumber with my releases path and in my nuget pack command, simply override the version with this.

If I need to rollback a version, I simply re-deploy the old release in Octopus and it will increment the release version. This also solves the pre-release issue on the version, as we no longer use the Octopus release number for the squirrel release. 

Example:

| Octopus Action | Squirrel Release           | 
| ------------- |-------------|
| Deploy 1.0.0      | 0.0.1|
| Deploy 1.1.0   | 0.0.2|  
| Re-deploy 1.0.0 | 0.0.3|   
| Deploy 1.2.0-alpha.1   | 0.0.4|  

Hope this helps someone!

**Comment by wjrogers** [comment]
Thank you for sharing this. I'm working on adopting Octopus and Squirrel for the first time, and I'm struggling with the lack of guidance on how to roll back to an older version in Squirrel. This is an absolute requirement for us because sometimes software has bugs and we have to pull a release. 

Can you be a little more specific about when/how you call your function? You said you use it on your pack step, but isn't the package already built when you deploy it using Octopus?

**Comment by markgould** [comment]
I actually use Octopack in the build step, and then I use the deploy package feature which extracts it into a folder on the octopus tentacle. I then have a package step that creates a nuspec file, and then call squirrel.

**Comment by wjrogers** [comment]
Ok, so you repack just for squirrel using a different version number, but upstream of that, Octopus is keeping track of what "real" version number is deployed. That might work for me, too. Thanks again!

**Comment by vadian** [comment]
This is a great workaround for me, as well.  Ideally, I'd like Squirrel to push whichever version we currently have tagged as live, and keep the version numbers intact, but this definitely tackles the main issue, rolling back through octopus so our devs can spend time fixing problems rather than creating rollback releases.

**Comment by shiftkey** [comment]
Closing this out in favour of the older discussion about rollback strategies in #524 - thanks for the insight @markgould!
