### ISSUE TITLE
What is Squirrel doing to my exe files?

### ISSUE THREAD

**Issue by Cheesebaron** [Squirrel/Squirrel.Windows#987]
I want to create an installer for a WPF application, the files consist of a bunch of dll's + 2 exe files.

1 exe for the WPF application itself and 1 for CefSharp.BrowserSubprocess.exe

What I am having trouble with is the last exe. When I want to show a CefSharp browser in the WPF app it fails complaining not being able to find the CefSharp.BrowserSubprocess.exe.

Looking at the install folder I have:

- app-0.1.0
- packages
- CefSharp.BrowserSubprocess.exe
- MyApp.exe
- Update.exe

inside of app-0.1.0 it also contains CefSharp.BrowserSubprocess.exe.

The one in the root folder is 199 KB while the one in app-0.1.0 is 19 KB. Looking at that particular file before running Squirrel --releasify that particular exe file was only 8 KB.

What is Squirrel doing to that exe file?

I was hoping making MyApp SquirrelAware would help it from touching other exe files, but it that hasn't helped, except for now I can control not to create a shortcut for the CefSharp.BrowserSubprocess.exe file.

**Comment by lukeskinner** [comment]
I see the same thing since updating to 1.5.x. My workaround for the moment is to embed secondary .exes like CefSharp.BrowserSubprocess.exe into my exe and then write them into the folder on startup on your application (MyApp.exe). Something else to note is that it also automatically launches additional .exes, so I see windows error reports from it launching .exes it shouldn't have launched. 

I have some time next week to find the actual bug, so if it's not fixed by then I'll submit a pr. 

I'm not sure on the file sizes, I haven't experienced that myself. The root app one will never match, its effectively a launcher for your program. The one inside app-0.1.0 should be the same as before releasify.

**Comment by Cheesebaron** [comment]
So similar to @lukeskinner's solution. I am now renaming my EXE files to something else before chucking them into the nuget file. Then in `onInitialInstall` and `onAppUpdate` I scan the folder for renamed exe files and rename them back. Now stuff, such as the CefSharp.BrowserSubprocess works again.

This is obviously a workaround to a problem with Squirrel.Windows, which seems to be related to what was implemented in https://github.com/Squirrel/Squirrel.Windows/pull/868

**Comment by MrBjorn** [comment]
The installation changes my real exe, i did a file compare, and the files is not identitcal? Once installed my exe also dont start, neither your stub or the real one.

**Comment by Thieum** [comment]
fixed by #1016
