### ISSUE TITLE
Using password-protected path in UpdateManager

### ISSUE THREAD

**Issue by dimon82** [Squirrel/Squirrel.Windows#992]
What's the best practices here? Is everyone just making the Releases path public? If I have a NAS or shared drive that you need to enter credentials for to access it, how can I use it for UpdateManager path?

**Comment by tehnetaholic** [comment]
@dimon82 Hi, Dmitry
In my case our users and our devs are not in domain (thought devs have domain accounts), so I did the following:
1. I set up a shared folder on Windows Server machine
2. Turned on anonymous guests on windows server policies.
3. Added read-only rights to a shared forder for anonymous users.
4. Added full rights to the same folder for devs.

Now anyone on our network can view files on this folder, but only devs can change them.
I had a small issue that dev couldn't authorise on the folder, and they were treated as anonymous.
Suprisingly simple solution was to navigate to \\our-local-server\\c$
Then we were prompted with autentication window and shared folder began to recognize us as devs.

Currently around 200 users are using an app deployed this way and get updates.
Another issue I encountered is that if you logged in on server via rdp and you open some of deployed files (nupkg, RELEASES, setup.exe), then other devs will fail to releasify, probably since windows server locaks opened file.

**Comment by stephenegriffin** [comment]
You can create and configure a WebClient object, pass that to a FileDownloader object, then pass that into UploadManager. You now have direct control over auth through your WebClient. I use this for ADAL against Azure.

**Comment by InteXX** [comment]
@stephenegriffin 

> You now have direct control over auth through your WebClient

I know it's been a while since you posted this, but would you happen to have a small code snippet demonstrating your technique? I'm very interested in this, particularly for deploying credential-protected updates on Azure Storage.

**Comment by stephenegriffin** [comment]
Something like this:
`
var authContext = new Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext(authority);  
var token = await authContext.AcquireTokenAsync(resource, clientId, redirectUri, noPromptParameters);  
var client = new System.WebClient();  
client.Headers.Add(HttpRequestHeader.Authorization, $"Bearer {token}");  
var fileDownloader = new Squirrel.FileDownloader(client);  
var updateManager = new Squirrel.UpdateManager(updateURL, urlDownloader: fileDownloader);  
`

**Comment by InteXX** [comment]
@stephenegriffin 

Looks good, thanks. I'll have a go at it.
